### ISSUE TITLE
Save bigram scores

### ISSUE THREAD

**Issue by fohrloop** [fohrloop/granite-tools#19]
Currently, when fitting bigram score ratio data to calculate bigram scores, a `bigram-anchor-raw-scores.json` is saved. This needs to be used together with a `bigram.ranking` file. It would be better to save just a single file with bigram (and unigram scores). For good intercompatibility, could use JSON or YAML format. The saved file could be for example `bigram.scores.yml`, with following data:

```yml
- key_indices: [8, 5]
  score: 1.28
  # left: DF
  # right: KJ
- key_indices: [9, 1]
  score: 2.21
  # left: CT
  # right: ,Y
- key_indices: [15, 13]
  score: 6.51
  # left: ZQ
  # right: /P
```

The "left" and "right" are nice additions for debugging (manually checking score with CTRL+F). Not sure if the fields should be added to the file. The scores are not tied to specific layout (the symbols), but to the key indices. As JSON this could be:

```json
[
    {
        "key_indices": [8, 5],
        "score": 1.28,
        "__comment__left": "DF",
        "__comment__right": "KJ"
    },
    {
        "key_indices": [9, 1],
        "score": 2.21,
        "__comment__left": "CT",
        "__comment__right": ",Y"
    },
    {
        "key_indices": [15, 13],
        "score": 6.51,
        "__comment__left": "ZQ",
        "__comment__right": "/P"
    }
]
```

this would it make clear that the symbols shown are just for debugging (comments).
